config/routes.rb
Rails.application.routes.draw do
  resources :members do
    member do
      post :add_friends
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: 'Member'
end

app/models/member.rb
class Member < ApplicationRecord
  serialize :headings

  has_many :friendships

  validates :name, presence: true, uniqueness: true
  validates :url, :short_url, presence: true

  def decorate
    MemberDecorator.new self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:add_friends, :edit, :update, :destroy, :search]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.map(&:decorate)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id]).decorate
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    form = MemberForm.new Member.new, member_params
    @member = form.member

    respond_to do |format|
      if form.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_friends
    add_friends_form = AddFriendsForm.new(@member, member_params[:friends])

    respond_to do |format|
      if add_friends_form.save
        format.html { redirect_to @member, notice: 'Friends were successfully added.'}
      else
        format.html { redirect_to @member, alert: 'Some errors occured.'}
      end
    end
  end

  def search
    respond_to do |format|
      format.json { render json: { result: ArticlesSearch.new(@member, params[:query]).search } }
      format.html { redirect_to @member }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :url, friends: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMembers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short url</th>
      <th>Friends</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.short_url %></td>
        <td><%= member.friends.count %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @member.url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @member.short_url %>
</p>

<p>
  <strong>Headings:</strong>
  <%= @member.headings %>
</p>

<% if @member.friends.any? %>
  <p>
    <strong>Friends:</strong>
    <ul>
      <% @member.friends.each do |friend| %>
        <li><%= link_to friend.name, member_path(friend) %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<% if @member.possible_friends.any? %>
  <p>
    <strong>You may know them:</strong>
    <%= form_tag add_friends_member_path(@member), method: :post do %>
      <ul>
        <% @member.possible_friends.each do |friend| %>
          <li>
            <span><%= friend.name %></span>
            <%= check_box 'member', 'friends', { multiple: true }, friend.id, nil %>
          </li>
        <% end %>
        <%= submit_tag I18n.t('add_friends') %>
      </ul>
    <% end %>
  </p>
<% end %>

<p>
  <strong>Search articles:</strong>
  <%= text_field_tag :query, nil, { class: 'search-input' } %>
  <%= hidden_field_tag :id, @member.id, { class: 'search-member-id' } %>
  <%= button_tag 'Search', class: 'search-btn' %>
  <div class='search-results'></div>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>